version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy

  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
  
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user

  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
    